
package com.seta.engine;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OtpService", targetNamespace = "http://engine.seta.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OtpService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.HelloResponse")
    @Action(input = "http://engine.seta.com/OtpService/helloRequest", output = "http://engine.seta.com/OtpService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param ric
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.InsertResponse")
    @Action(input = "http://engine.seta.com/OtpService/insertRequest", output = "http://engine.seta.com/OtpService/insertResponse")
    public String insert(
        @WebParam(name = "ric", targetNamespace = "")
        Richiesta ric);

    /**
     * 
     * @param ver
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://engine.seta.com/", className = "com.seta.engine.VerifyResponse")
    @Action(input = "http://engine.seta.com/OtpService/verifyRequest", output = "http://engine.seta.com/OtpService/verifyResponse")
    public String verify(
        @WebParam(name = "ver", targetNamespace = "")
        Verifica ver);

}
